"""alex auto

Revision ID: 5ea58e3a4624
Revises: 942d824b1ab1
Create Date: 2026-09-21 10:46:06.167781

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ea58e3a4624'
down_revision: str | None = '942d824b1ab1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketing_activities_activity_date'), table_name='marketing_activities')
    op.drop_table('marketing_activities')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketing_activities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('activity_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('activity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('campaign_code', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('dynamic_fields', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['marketing_team_members.id'], name=op.f('marketing_activities_created_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('marketing_activities_pkey')),
    sa.UniqueConstraint('activity_date', 'activity_type', name=op.f('uq_activity_date_type'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('campaign_code', name=op.f('marketing_activities_campaign_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_marketing_activities_activity_date'), 'marketing_activities', ['activity_date'], unique=False)
    # ### end Alembic commands ###
