"""alex auto

Revision ID: 942d824b1ab1
Revises: 0003_marketing_activities
Create Date: 2026-09-18 15:59:49.817035

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '942d824b1ab1'
down_revision: str | None = '0003_marketing_activities'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketing_team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_authorized', sa.Boolean(), nullable=False),
    sa.Column('has_performance_access', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_team_members_email'), 'marketing_team_members', ['email'], unique=True)
    op.create_index(op.f('ix_marketing_team_members_username'), 'marketing_team_members', ['username'], unique=True)
    op.create_table('marketing_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('campaign_code', sa.String(length=32), nullable=False),
    sa.Column('dynamic_fields', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['marketing_team_members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_date', 'activity_type', name='uq_activity_date_type'),
    sa.UniqueConstraint('campaign_code')
    )
    op.create_index(op.f('ix_marketing_activities_activity_date'), 'marketing_activities', ['activity_date'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['marketing_team_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    # Drop legacy tables in FK-safe order (dependents before users).
    op.drop_index(op.f('ix_activity_audit_logs_activity_created'), table_name='activity_audit_logs')
    op.drop_index(op.f('ix_activity_audit_logs_created_at'), table_name='activity_audit_logs')
    op.drop_table('activity_audit_logs')
    op.drop_table('activities')
    op.drop_index(op.f('ix_klaviyo_notifications_user_created'), table_name='klaviyo_retrieval_notifications')
    op.drop_table('klaviyo_retrieval_notifications')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_audit_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('activity_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('activity_title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('activity_audit_logs_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('activity_audit_logs_pkey'))
    )
    op.create_index(op.f('ix_activity_audit_logs_created_at'), 'activity_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_audit_logs_activity_created'), 'activity_audit_logs', ['activity_id', 'created_at'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('activity_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('activity_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('additional_info', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('campaign_code', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('activities_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('activities_pkey')),
    sa.UniqueConstraint('activity_date', 'activity_type', name=op.f('uq_activities_date_type'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('password_reset_token_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('password_reset_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('users_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('klaviyo_retrieval_notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('klaviyo_retrieval_notifications_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('klaviyo_retrieval_notifications_pkey'))
    )
    op.create_index(op.f('ix_klaviyo_notifications_user_created'), 'klaviyo_retrieval_notifications', ['user_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_marketing_activities_activity_date'), table_name='marketing_activities')
    op.drop_table('marketing_activities')
    op.drop_index(op.f('ix_marketing_team_members_username'), table_name='marketing_team_members')
    op.drop_index(op.f('ix_marketing_team_members_email'), table_name='marketing_team_members')
    op.drop_table('marketing_team_members')
    # ### end Alembic commands ###
